Document: idleshutdowner
Title: Debian idleshutdowner Manual
Author: <insert document author here>
Abstract: This manual describes what idleshutdowner is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/idleshutdowner/idleshutdowner.sgml.gz

Format: postscript
Files: /usr/share/doc/idleshutdowner/idleshutdowner.ps.gz

Format: text
Files: /usr/share/doc/idleshutdowner/idleshutdowner.text.gz

Format: HTML
Index: /usr/share/doc/idleshutdowner/html/index.html
Files: /usr/share/doc/idleshutdowner/html/*.html
